install.packages("limma")
library(limma)
targets <- readTargets("Targets.txt")
RG <- read.maimages(targets$FileName, source="agilent")
files <- targets[,c("Cy3","Cy5")] 
x <- read.maimages(targets, source="agilent", green.only=TRUE)
summary(x$E)
x <- read.maimages(targets, source="agilent.mean", green.only=TRUE)
plotMD(RG)
boxplot(data.frame(log2(RG$Gb)),main="Green background")
boxplot(data.frame(log2(RG$Rb)),main="Red background")
imageplot(log2(RG$Gb[,1]),RG$printer)
plotMD(RG, array=2, main="Sample 2")
plotMD(RG, array=3, main="Sample 3")
plotMD(RG, array=4, main="Sample 4")
plotMD(RG, array=5, main="Sample 5")
plotMD(RG, array=6, main="Sample 6")
plotDensities(log2(RG$G))   # green channel raw data
plotDensities(log2(RG$R))   # red channel raw data (if 2-color)
plotMD(RG)
plotDensities(RG)
MA.p <-normalizeWithinArrays(RG) 
plotDensities(MA.p)
MA.pAq <- normalizeBetweenArrays(MA.p, method="Aquantile")
plotDensities(MA.pAq)
MA.q <- normalizeBetweenArrays(RG, method="quantile") 
plotDensities(MA.q, col="black")
